language: php
php:
  - '7.0'

before_script:
  - wget https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer-v2
  - chmod a+x php-cs-fixer-v2

script:
  - ./php-cs-fixer-v2 fix /app --diff --dry-run -vvv
